
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UDEOExceptionless
{

using System;
    using System.Collections.Generic;
    
public partial class Donacion
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Donacion()
    {

        this.donacion_balance = new HashSet<donacion_balance>();

    }


    public int Id { get; set; }

    public int Cliente_id { get; set; }

    public decimal Mes { get; set; }

    public decimal Anio { get; set; }

    public decimal Donacion1 { get; set; }



    public virtual Cliente Cliente { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<donacion_balance> donacion_balance { get; set; }

}

}
